### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by Cryptomoment** [polkascan/explorer#27]
explorer-harvester-1  | 2023-04-10 13:45:50 🟢 Job "scale_decode" started                                
explorer-harvester-1  | Traceback (most recent call last):
explorer-harvester-1  |   File "app/cli.py", line 141, in <module>
explorer-harvester-1  |     main()
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
explorer-harvester-1  |     return self.main(*args, **kwargs)
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
explorer-harvester-1  |     rv = self.invoke(ctx)
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
explorer-harvester-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
explorer-harvester-1  |     return ctx.invoke(self.callback, **ctx.params)
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
explorer-harvester-1  |     return __callback(*args, **kwargs)
explorer-harvester-1  |   File "app/cli.py", line 61, in run
explorer-harvester-1  |     harvester.run(job)
explorer-harvester-1  |   File "/usr/src/app/harvester.py", line 339, in run
explorer-harvester-1  |     self.process_job('scale_decode')
explorer-harvester-1  |   File "/usr/src/app/harvester.py", line 295, in process_job
explorer-harvester-1  |     self.jobs[name].start()
explorer-harvester-1  |   File "/usr/src/app/jobs.py", line 837, in start
explorer-harvester-1  |     self.decode_extrinsic(node_extrinsic)
explorer-harvester-1  |   File "/usr/src/app/jobs.py", line 916, in decode_extrinsic
explorer-harvester-1  |     self.db_substrate.init_runtime(block_hash=f'0x{node_block_extrinsic.block_hash.hex()}')
explorer-harvester-1  |   File "/usr/src/app/base.py", line 251, in init_runtime
explorer-harvester-1  |     super().init_runtime(*args, **kwargs)
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/substrateinterface/base.py", line 667, in init_runtime
explorer-harvester-1  |     runtime_info = self.get_block_runtime_version(block_hash=runtime_block_hash)
explorer-harvester-1  |   File "/usr/local/lib/python3.8/site-packages/substrateinterface/base.py", line 571, in get_block_runtime_version
explorer-harvester-1  |     response = self.rpc_request("state_getRuntimeVersion", [block_hash])
explorer-harvester-1  |   File "/usr/src/app/base.py", line 248, in rpc_request
explorer-harvester-1  |     raise ValueError("No handler for method '{}'".format(method))
explorer-harvester-1  | ValueError: No handler for method 'state_getRuntimeVersion'
explorer-harvester-1 exited with code 0

**Comment by arjanz** [comment]
I added the missing RPC method `state_getRuntimeVersion` to the abstraction layer used by the harvester (used in some versions of Substrate). Is it working for you now?
