### ISSUE TITLE
How to connect a custom chain

### ISSUE THREAD

**Issue by didiermis** [polkascan/explorer#3]
Hey,
I was wondering how can I setup a connection to a custom chain, using the following wss:
wss://n1.polka.systems

**Comment by arjanz** [comment]
Have you tried replacing the `SUBSTRATE_RPC_URL ` variable in https://github.com/polkascan/explorer/blob/main/docker-compose.yml#L14 and have a go? For most Substrate based chains it should work out of the box.

**Comment by didiermis** [comment]
Isn't working, is still running the docker image. 
I got this error when I change the wss:
```python
harvester_1       | Traceback (most recent call last):
harvester_1       |   File "app/harvester.py", line 394, in <module>
harvester_1       |     harvester.run(args.action)
harvester_1       |   File "app/harvester.py", line 292, in run
harvester_1       |     self.init()
harvester_1       |   File "app/harvester.py", line 237, in init
harvester_1       |     raise ValueError(
harvester_1       | ValueError: Connected chain 'Polka Systems - Chaos' does not match chain 'Development' in database
```
Can you help me?

**Comment by arjanz** [comment]
Then probably you changed the endpoint for an existing database used on another chain, you will need to flush the current database or create a new one for this chain..

**Comment by didiermis** [comment]
Thank you @arjanz, I'm not an experioenced developer, sorry if this questions sounds dumb but,
As far as I understand, the steps I need to follow:
- Clone repo
-  Run ` ./init.sh`
- Change the endpoint 
`SUBSTRATE_RPC_URL=wss://n1.polka.systems`
- Run `docker-compose up --build`
- Go to: `Polkascan UI: http://127.0.0.1:8080/`
Am I missing something? 
Do I need to configure my own local DB?
I greatly appreciate your help.

**Comment by didiermis** [comment]
Morning, 
The other day I was trying the following (using the original code connected to the node template):
- Clone repo
- Run `./init.sh`
- Run `docker-compose up --build`
- Press `ctrl + c` to stop it
-  Run again `docker-compose up --build` 
- HERE: It says a problem related to MySQL: 
- 
![image](https://user-images.githubusercontent.com/62629075/188915177-5963d516-83b6-4557-a3e0-97e87261975d.png)


After this, I tried the page u mentioned above: https://docs.tibco.com/pub/mash-local/4.3.0/doc/html/docker/GUID-BD850566-5B79-4915-987E-430FC38DAAE4.html
The new process: 
- Clone repo
- Run `./init.sh`
- Run `docker-compose up --build`
- Press `ctrl + c` to stop it
- Restart containers/volumes
-  Run again `docker-compose up --build`
- Same problem with MySQL.


My restart script looks like this:
```bash
echo "Stop the container(s) using the following command:"
docker-compose down --volumes

echo "Delete all containers using the following command:"
docker rm -f $(docker ps -a -q)

echo "Delete all volumes using the following command:"
docker volume rm $(docker volume ls -q)

echo "Restart the containers using the following command:"
docker-compose up -d
```
I also tried deleting all Docker images and containers (it takes a long time to build the project) with no success:
- `docker rmi $(docker images -a -q)`
- `docker volume prune`

What am I missing here? Thanks in advance.

**Comment by wouterter** [comment]
Are you still having problems with this?
